# Generated by Django 5.2.8 on 2026-09-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Simpliers Giveaway', max_length=255)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('multi', 'Multi-Post'), ('list', 'List Tool')], default='instagram', max_length=50)),
                ('post_url', models.URLField(blank=True, default='', max_length=500)),
                ('account_username', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('winner_count', models.PositiveIntegerField(default=1)),
                ('substitute_count', models.PositiveIntegerField(default=1)),
                ('min_mentions', models.PositiveIntegerField(default=0)),
                ('keyword_filter', models.CharField(blank=True, default='', max_length=100)),
                ('allow_duplicates', models.BooleanField(default=False)),
                ('certificate_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('verification_hash', models.CharField(blank=True, default='', max_length=64)),
                ('total_entries_count', models.PositiveIntegerField(default=0)),
                ('eligible_entries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('comment_text', models.TextField(blank=True, default='')),
                ('mentions_count', models.PositiveIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_substitute', models.BooleanField(default=False)),
                ('win_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='giveaways.giveaway')),
            ],
            options={
                'ordering': ['win_order', 'id'],
            },
        ),
    ]
