# Generated by Django 5.2.8 on 2026-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiggedWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_value', models.CharField(help_text='The value to match in the entries (e.g. name, email, or a whole row).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
